export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL';
export const PRODUCT_FETCH = 'PRODUCT_FETCH';
export const INTERNET_CONNECTION_FAIL = 'INTERNET_CONNECTION_FAIL';
export const LOADING_CHANGE = 'LOADING_CHANGE';
